### ISSUE TITLE
pip3 backtrace incorrectly triggers spamfilter

### ISSUE THREAD

**Issue by divinity76** [formorer/paste.pl#15]
the following text will (incorrectly) trigger the spamfilter, observed on http://paste.debian.net/  at 2020-03-20 09:30 UTC

```

$ pip install --upgrade pip
Requirement already up-to-date: pip in /usr/lib/python3.6/site-packages (20.0.2)

$ pip install pycurl
Collecting pycurl
  Downloading pycurl-7.43.0.5.tar.gz (216 kB)
     |████████████████████████████████| 216 kB 630 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-29ydc5y4/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-29ydc5y4/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-29ydc5y4/pycurl/pip-egg-info
         cwd: /tmp/pip-install-29ydc5y4/pycurl/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-29ydc5y4/pycurl/setup.py", line 234, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-29ydc5y4/pycurl/setup.py", line 961, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-29ydc5y4/pycurl/setup.py", line 623, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-29ydc5y4/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-29ydc5y4/pycurl/setup.py", line 238, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by josch** [comment]
try replacing `child` with `chi1ld` (or something else) and you can finally "spam" again...

**Comment by divinity76** [comment]
> try replacing `child` with `chi1ld` (or something else) and you can finally "spam" again...

I don't want to bypass the bug, I want to see the bug fixed.
